export const mock = [
    {
        "tweet_id": "1577653730631000065",
        "creation_date": "Wed Oct 05 13:35:35 +0000 2022",
        "text": ".@tetu_io team has been busy building V2 and multiple new products .\n\nOur Founder @belbix explains upcoming plans for tetu and what the future holds \nhttps://t.co/erffClKAUw",
        "media_url": null,
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 20,
        "retweet_count": 9,
        "reply_count": 4,
        "quote_count": 3,
        "retweet": false,
        "timestamp": 1664976935,
        "video_view_count": null
    },
    {
        "tweet_id": "1569293496326012930",
        "creation_date": "Mon Sep 12 11:55:00 +0000 2022",
        "text": "Tetu's portfolio is now tracked on https://t.co/IEGJ3zLnSg! (@BNBCHAIN version)\n\nHat tip to all @tetu_io voters! $TETU\nhttps://t.co/t2pDRrdmb3 https://t.co/83gkFftaDP",
        "media_url": null,
        "video_url": null,
        "user": {
            "creation_date": "Tue Jul 30 03:03:37 +0000 2019",
            "user_id": null,
            "username": "DeBankDeFi",
            "name": "DeBank",
            "follower_count": 75930,
            "following_count": 3704,
            "is_private": false,
            "is_verified": false,
            "location": "ETH,BSC,AVAX,MATIC,MOVR...",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1414880725921267716/YzVitob7_normal.jpg",
            "description": "The leading Web3 portfolio tracker that supports the largest number of DeFi protocols across 37 chains.",
            "external_url": "https://DeBank.com",
            "number_of_tweets": 3491,
            "bot": false,
            "timestamp": null,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 42,
        "retweet_count": 18,
        "reply_count": 2,
        "quote_count": 1,
        "retweet": true,
        "timestamp": 1662983700,
        "video_view_count": null
    },
    {
        "tweet_id": "1567791621554733056",
        "creation_date": "Thu Sep 08 08:27:05 +0000 2022",
        "text": "Tetu is open 24/7. You're always earning the best yields defi has to offer\n🟡 $WBNB - $BUSD: 13k% APY\n🟡$CONE - $WBNB: 14M% APY\n🟡$WBNB - $USD+: 14M% APY\n👉 https://t.co/WOOdyH7HFw\n\n@Coneswap \n@overnight_fi \n@binance https://t.co/512nrapDFE",
        "media_url": [
            "https://pbs.twimg.com/media/FcHph9YaQAIE2RR.jpg"
        ],
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 23,
        "retweet_count": 9,
        "reply_count": 1,
        "quote_count": 1,
        "retweet": false,
        "timestamp": 1662625625,
        "video_view_count": null
    },
    {
        "tweet_id": "1565248133285613568",
        "creation_date": "Thu Sep 01 08:00:10 +0000 2022",
        "text": "Excited to work together with @Stabl_Fi on @0xPolygon  and use their Upcoming stablecoin $CASH+ to build new farming strategies . Keep an eye out for their launch soon! https://t.co/kwp9rFBRx5",
        "media_url": [
            "https://pbs.twimg.com/media/FbjgYUDUcAAtyas.jpg"
        ],
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 23,
        "retweet_count": 10,
        "reply_count": 1,
        "quote_count": 0,
        "retweet": false,
        "timestamp": 1662019210,
        "video_view_count": null
    },
    {
        "tweet_id": "1562636108579876864",
        "creation_date": "Thu Aug 25 03:00:55 +0000 2022",
        "text": "Looking for a high #APR on @Coneswap ? Search no longer! Maximize your $CONE yields with our new vaults, powered by #Tetu🧑‍🌾\n\n🔹$CONE / $BNB LP: ~♾ APR\n\n👇Deposit and Grow your 💵:\nhttps://t.co/WOOdyH7HFw\n\n #BSC #BNB https://t.co/H5WRUWuC2K",
        "media_url": [
            "https://pbs.twimg.com/media/Fa-YvorXEAAqYBs.jpg"
        ],
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 39,
        "retweet_count": 12,
        "reply_count": 4,
        "quote_count": 1,
        "retweet": false,
        "timestamp": 1661396455,
        "video_view_count": null
    },
    {
        "tweet_id": "1562556215892160512",
        "creation_date": "Wed Aug 24 21:43:27 +0000 2022",
        "text": "If you've been following the Tetuan ecosystem, you've noticed that we've launched on #BNB &amp; got our token listed on @Coneswap. 🏦 \n\nThis was made possible by our #DEX, with whom we own a veNFT. Enjoy our new strategy centered around $CONE. 💰 https://t.co/KzmhRnO8kt",
        "media_url": [
            "https://pbs.twimg.com/media/Fa9Qk9oWIAAtw3n.jpg"
        ],
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 46,
        "retweet_count": 16,
        "reply_count": 3,
        "quote_count": 1,
        "retweet": false,
        "timestamp": 1661377407,
        "video_view_count": null
    },
    {
        "tweet_id": "1559644897279283200",
        "creation_date": "Tue Aug 16 20:54:54 +0000 2022",
        "text": "Now tracking @tetu_io pools on Yield Dashboard\n\nhttps://t.co/8uN2r7yKQE https://t.co/k9H8fwuTSu",
        "media_url": null,
        "video_url": null,
        "user": {
            "creation_date": "Wed Oct 28 22:52:25 +0000 2020",
            "user_id": null,
            "username": "DefiLlama",
            "name": "DefiLlama.com",
            "follower_count": 127482,
            "following_count": 117,
            "is_private": false,
            "is_verified": false,
            "location": "",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1377743719089254405/LQwS_x0l_normal.jpg",
            "description": "Open and transparent DeFi TVL and analytics.\n\nDeFi Updates: https://t.co/aaN9I6wbcL | Join the community: https://t.co/IIf3mE8UU2",
            "external_url": "http://t.me/defillama_tg",
            "number_of_tweets": 3647,
            "bot": false,
            "timestamp": null,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 17,
        "retweet_count": 6,
        "reply_count": 0,
        "quote_count": 2,
        "retweet": true,
        "timestamp": 1660683294,
        "video_view_count": null
    },
    {
        "tweet_id": "1556990996075778049",
        "creation_date": "Tue Aug 09 13:09:15 +0000 2022",
        "text": "Join the next #Tetu #AMA with @belbix!📢\n\n⏰Time: 5pm (UTC) on August 10th\n🎯Place: @tetu_io Discord https://t.co/z22ECZgteT https://t.co/VhKod2rjej",
        "media_url": [
            "https://pbs.twimg.com/media/FZuKwarVUAAzDnT.jpg"
        ],
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 12,
        "retweet_count": 6,
        "reply_count": 1,
        "quote_count": 4,
        "retweet": false,
        "timestamp": 1660050555,
        "video_view_count": null
    },
    {
        "tweet_id": "1554967881267691520",
        "creation_date": "Wed Aug 03 23:10:07 +0000 2022",
        "text": "💙 Can you believe it's been 1 year since we've launched Tetu? We appreciate every single one of you who've invested in our team. 💜\n\nTetu V2 will come out stronger than ever, making everything we've built a Lego piece to rule them all! 👷\n\nhttps://t.co/x4irq1Ycme",
        "media_url": null,
        "video_url": null,
        "user": {
            "creation_date": "Wed Jun 16 12:38:55 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "tetu_io",
            "name": "Tetu",
            "follower_count": 6231,
            "following_count": 46,
            "is_private": false,
            "is_verified": false,
            "location": "Get Highest yield in DeFi →",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1478040475420352517/XZdZhhl2_normal.jpg",
            "description": "Multichain Web3 asset management protocol with highest yield in DeFi✨\n\nDiscord: https://t.co/jjFZajiXUE",
            "external_url": "http://discord.gg/r6qQRmD6Ka",
            "number_of_tweets": 415,
            "bot": false,
            "timestamp": 1623847135,
            "has_nft_avatar": false
        },
        "language": "en",
        "favorite_count": 19,
        "retweet_count": 5,
        "reply_count": 2,
        "quote_count": 3,
        "retweet": false,
        "timestamp": 1659568207,
        "video_view_count": null
    },
    {
        "tweet_id": "1554555116107497472",
        "creation_date": "Tue Aug 02 19:49:56 +0000 2022",
        "text": "More MAI👀",
        "media_url": null,
        "video_url": null,
        "user": {
            "creation_date": "Tue Jun 01 23:00:04 +0000 2021",
            "user_id": "1405142811800911872",
            "username": "QiDaoProtocol",
            "name": "Qi Dao",
            "follower_count": 30499,
            "following_count": 263,
            "is_private": false,
            "is_verified": false,
            "location": "decentralized",
            "profile_pic_url": "https://pbs.twimg.com/profile_images/1399870094767951882/mXiKwLy__normal.jpg",
            "description": "Creators of $MAI (miMatic) Stablecoin. Start borrowing at 0% interest against your crypto https://t.co/I5MrqACF3K",
            "external_url": "http://linktr.ee/0xlaozi",
            "number_of_tweets": 1880,
            "bot": false,
            "timestamp": 1622588404,
            "has_nft_avatar": false
        },
        "language": "fr",
        "favorite_count": 14,
        "retweet_count": 1,
        "reply_count": 1,
        "quote_count": 2,
        "retweet": false,
        "timestamp": 1659469796,
        "video_view_count": null
    },
]