export const ZapContractAbi = [
  {
    inputs: [
      { internalType: 'address', name: '_controller', type: 'address' },
      { internalType: 'address', name: '_multiSwap', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'oldValue', type: 'address' },
      { indexed: false, internalType: 'address', name: 'newValue', type: 'address' },
    ],
    name: 'UpdateController',
    type: 'event',
  },
  {
    inputs: [],
    name: 'VERSION',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'controller',
    outputs: [{ internalType: 'address', name: 'adr', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'created',
    outputs: [{ internalType: 'uint256', name: 'ts', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_controller', type: 'address' }],
    name: 'initializeControllable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_adr', type: 'address' }],
    name: 'isController',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_adr', type: 'address' }],
    name: 'isGovernance',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'multiSwap',
    outputs: [{ internalType: 'contract IMultiSwap', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_token', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'salvage',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_vault', type: 'address' },
      { internalType: 'address', name: '_tokenIn', type: 'address' },
      { internalType: 'address', name: '_asset', type: 'address' },
      { internalType: 'address[]', name: '_assetRoute', type: 'address[]' },
      { internalType: 'uint256', name: '_tokenInAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'slippageTolerance', type: 'uint256' },
    ],
    name: 'zapInto',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_vault', type: 'address' },
      { internalType: 'address', name: '_tokenIn', type: 'address' },
      { internalType: 'address', name: '_asset0', type: 'address' },
      { internalType: 'address[]', name: '_asset0Route', type: 'address[]' },
      { internalType: 'address', name: '_asset1', type: 'address' },
      { internalType: 'address[]', name: '_asset1Route', type: 'address[]' },
      { internalType: 'uint256', name: '_tokenInAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'slippageTolerance', type: 'uint256' },
    ],
    name: 'zapIntoLp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_vault', type: 'address' },
      { internalType: 'address', name: '_tokenOut', type: 'address' },
      { internalType: 'address', name: '_asset', type: 'address' },
      { internalType: 'address[]', name: '_assetRoute', type: 'address[]' },
      { internalType: 'uint256', name: '_shareTokenAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'slippageTolerance', type: 'uint256' },
    ],
    name: 'zapOut',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_vault', type: 'address' },
      { internalType: 'address', name: '_tokenOut', type: 'address' },
      { internalType: 'address', name: '_asset0', type: 'address' },
      { internalType: 'address[]', name: '_asset0Route', type: 'address[]' },
      { internalType: 'address', name: '_asset1', type: 'address' },
      { internalType: 'address[]', name: '_asset1Route', type: 'address[]' },
      { internalType: 'uint256', name: '_shareTokenAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'slippageTolerance', type: 'uint256' },
    ],
    name: 'zapOutLp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
]
